Pagination:
  NoOfEntriesPerPage: 15
BackgroundTask:
  SecondsBetweenTries: 20
  MaximumAmountOfTries: 3
Systems:
  NoOfShownRecentTasks: 10
  NotSeenWarningThresholdMinutes: 240
Tasks:
  OverdueWarningThresholdMinutes: 10
General:
  Timezone: "Bern" #use rake time:zones:all to see all available settings
